version: 2
updates:
  # .NET packages
  - package-ecosystem: "nuget"
    directory: "/Source"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "UTC"
    open-pull-requests-limit: 10
    reviewers:
      - "${{ github.repository_owner }}"
    assignees:
      - "${{ github.repository_owner }}"
    labels:
      - "dependencies"
      - "dotnet"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    ignore:
      # Ignore pre-release versions
      - dependency-name: "*"
        update-types: ["version-update:semver-prerelease"]
    groups:
      microsoft-aspnetcore:
        patterns:
          - "Microsoft.AspNetCore*"
        update-types:
          - "minor"
          - "patch"
      microsoft-entityframeworkcore:
        patterns:
          - "Microsoft.EntityFrameworkCore*"
        update-types:
          - "minor"
          - "patch"
      microsoft-extensions:
        patterns:
          - "Microsoft.Extensions*"
        update-types:
          - "minor"
          - "patch"
      testing-frameworks:
        patterns:
          - "xunit*"
          - "Microsoft.NET.Test.Sdk"
          - "coverlet.collector"
          - "nsubstitute"
          - "awesomeassertions"
        update-types:
          - "minor"
          - "patch"
      analyzers:
        patterns:
          - "Microsoft.CodeAnalysis*"
          - "SonarAnalyzer.CSharp"
          - "StyleCop.Analyzers"
          - "Roslynator.Analyzers"
        update-types:
          - "minor"
          - "patch"
      security-updates:
        patterns:
          - "*"
        update-types:
          - "security"

  # npm packages
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    reviewers:
      - "${{ github.repository_owner }}"
    assignees:
      - "${{ github.repository_owner }}"
    labels:
      - "dependencies"
      - "javascript"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    ignore:
      # Ignore pre-release versions
      - dependency-name: "*"
        update-types: ["version-update:semver-prerelease"]
    groups:
      playwright:
        patterns:
          - "@playwright/*"
          - "playwright"
        update-types:
          - "minor"
          - "patch"
      typescript:
        patterns:
          - "typescript"
          - "@types/*"
        update-types:
          - "minor"
          - "patch"
      eslint:
        patterns:
          - "eslint*"
          - "@typescript-eslint/*"
        update-types:
          - "minor"
          - "patch"
      build-tools:
        patterns:
          - "prettier"
          - "webpack*"
          - "vite*"
          - "rollup*"
        update-types:
          - "minor"
          - "patch"

  # Docker base images
  - package-ecosystem: "docker"
    directory: "/.devcontainer"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    reviewers:
      - "${{ github.repository_owner }}"
    assignees:
      - "${{ github.repository_owner }}"
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "deps"
      include: "scope"
    allow:
      - dependency-type: "direct"
    ignore:
      # Ignore beta and rc versions
      - dependency-name: "*"
        update-types: ["version-update:semver-prerelease"]

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    reviewers:
      - "${{ github.repository_owner }}"
    assignees:
      - "${{ github.repository_owner }}"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "deps"
      include: "scope"
    allow:
      - dependency-type: "direct"
    groups:
      actions-setup:
        patterns:
          - "actions/setup-*"
        update-types:
          - "minor"
          - "patch"
      actions-checkout:
        patterns:
          - "actions/checkout"
          - "actions/upload-artifact"
          - "actions/download-artifact"
          - "actions/cache"
        update-types:
          - "minor"
          - "patch"
      docker-actions:
        patterns:
          - "docker/*"
        update-types:
          - "minor"
          - "patch"