// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace MCPHub.IntegrationTests.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class SecurityScanningAndTrustTierManagementFeature : object, Xunit.IClassFixture<SecurityScanningAndTrustTierManagementFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "SecurityScanning.feature"
#line hidden
        
        public SecurityScanningAndTrustTierManagementFeature(SecurityScanningAndTrustTierManagementFeature.FixtureData fixtureData, MCPHub_IntegrationTests_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en"), "Features", "Security Scanning and Trust Tier Management", "  In order to ensure platform security and user trust\n  As a security administrat" +
                    "or or package consumer\n  I want packages to be automatically scanned and assigne" +
                    "d appropriate trust tiers", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 6
  #line hidden
#line 7
    testRunner.Given("the MCP Hub API is running", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 8
    testRunner.And("the security scanning service is available", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 9
    testRunner.And("the database is initialized with test data", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Automatic security scan on package publish")]
        [Xunit.TraitAttribute("FeatureTitle", "Security Scanning and Trust Tier Management")]
        [Xunit.TraitAttribute("Description", "Automatic security scan on package publish")]
        [Xunit.TraitAttribute("Category", "api")]
        [Xunit.TraitAttribute("Category", "security")]
        [Xunit.TraitAttribute("Category", "scanning")]
        [Xunit.TraitAttribute("Category", "automatic")]
        public void AutomaticSecurityScanOnPackagePublish()
        {
            string[] tagsOfScenario = new string[] {
                    "api",
                    "security",
                    "scanning",
                    "automatic"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Automatic security scan on package publish", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 12
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
  this.FeatureBackground();
#line hidden
#line 13
    testRunner.Given("I am authenticated as a publisher", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 14
    testRunner.And("I have a clean package manifest and files", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 15
    testRunner.When("I publish a new package", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 16
    testRunner.Then("the package should be created successfully", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 17
    testRunner.And("a security scan should be automatically initiated", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 18
    testRunner.And("the scan status should be \"In Progress\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 19
    testRunner.And("I should receive a scan ID for tracking", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Security scan completion with clean results")]
        [Xunit.TraitAttribute("FeatureTitle", "Security Scanning and Trust Tier Management")]
        [Xunit.TraitAttribute("Description", "Security scan completion with clean results")]
        [Xunit.TraitAttribute("Category", "api")]
        [Xunit.TraitAttribute("Category", "security")]
        [Xunit.TraitAttribute("Category", "scanning")]
        [Xunit.TraitAttribute("Category", "completion")]
        public void SecurityScanCompletionWithCleanResults()
        {
            string[] tagsOfScenario = new string[] {
                    "api",
                    "security",
                    "scanning",
                    "completion"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Security scan completion with clean results", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 22
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
  this.FeatureBackground();
#line hidden
#line 23
    testRunner.Given("I have published a package that is being scanned", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 24
    testRunner.When("the security scan completes successfully", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 25
    testRunner.Then("the package should have scan results attached", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 26
    testRunner.And("the package should be assigned a trust tier based on scan results", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 27
    testRunner.And("the security score should be calculated and stored", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 28
    testRunner.And("the package status should be updated to reflect scan completion", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Security scan detects vulnerabilities")]
        [Xunit.TraitAttribute("FeatureTitle", "Security Scanning and Trust Tier Management")]
        [Xunit.TraitAttribute("Description", "Security scan detects vulnerabilities")]
        [Xunit.TraitAttribute("Category", "api")]
        [Xunit.TraitAttribute("Category", "security")]
        [Xunit.TraitAttribute("Category", "scanning")]
        [Xunit.TraitAttribute("Category", "vulnerabilities")]
        public void SecurityScanDetectsVulnerabilities()
        {
            string[] tagsOfScenario = new string[] {
                    "api",
                    "security",
                    "scanning",
                    "vulnerabilities"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Security scan detects vulnerabilities", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 31
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
  this.FeatureBackground();
#line hidden
#line 32
    testRunner.Given("I have published a package with known security issues", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 33
    testRunner.When("the security scan completes", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 34
    testRunner.Then("the scan should detect the security vulnerabilities", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 35
    testRunner.And("each vulnerability should have severity, description, and recommendations", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 36
    testRunner.And("the package trust tier should reflect the security issues", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 37
    testRunner.And("the package should be flagged for review if critical issues found", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Static code analysis scanning")]
        [Xunit.TraitAttribute("FeatureTitle", "Security Scanning and Trust Tier Management")]
        [Xunit.TraitAttribute("Description", "Static code analysis scanning")]
        [Xunit.TraitAttribute("Category", "api")]
        [Xunit.TraitAttribute("Category", "security")]
        [Xunit.TraitAttribute("Category", "scanning")]
        [Xunit.TraitAttribute("Category", "static")]
        public void StaticCodeAnalysisScanning()
        {
            string[] tagsOfScenario = new string[] {
                    "api",
                    "security",
                    "scanning",
                    "static"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Static code analysis scanning", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 40
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
  this.FeatureBackground();
#line hidden
#line 41
    testRunner.Given("I have a package with various code patterns", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 42
    testRunner.When("the static analysis scan runs", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 43
    testRunner.Then("it should analyze code for security patterns", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table27 = new TechTalk.SpecFlow.Table(new string[] {
                            "Vulnerability Type",
                            "Pattern"});
                table27.AddRow(new string[] {
                            "Code Injection",
                            "eval(), Function()"});
                table27.AddRow(new string[] {
                            "Path Traversal",
                            "../, \\..\\"});
                table27.AddRow(new string[] {
                            "Hardcoded Secrets",
                            "API keys, passwords"});
                table27.AddRow(new string[] {
                            "Unsafe Dependencies",
                            "Known vulnerable packages"});
#line 44
    testRunner.And("it should detect potential vulnerabilities like:", ((string)(null)), table27, "And ");
#line hidden
#line 50
    testRunner.And("findings should be categorized by severity", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 51
    testRunner.And("recommendations should be provided for remediation", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Dynamic security analysis in sandbox")]
        [Xunit.TraitAttribute("FeatureTitle", "Security Scanning and Trust Tier Management")]
        [Xunit.TraitAttribute("Description", "Dynamic security analysis in sandbox")]
        [Xunit.TraitAttribute("Category", "api")]
        [Xunit.TraitAttribute("Category", "security")]
        [Xunit.TraitAttribute("Category", "scanning")]
        [Xunit.TraitAttribute("Category", "dynamic")]
        public void DynamicSecurityAnalysisInSandbox()
        {
            string[] tagsOfScenario = new string[] {
                    "api",
                    "security",
                    "scanning",
                    "dynamic"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Dynamic security analysis in sandbox", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 54
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
  this.FeatureBackground();
#line hidden
#line 55
    testRunner.Given("I have a package that needs dynamic analysis", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 56
    testRunner.When("the dynamic security scan runs", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 57
    testRunner.Then("the package should be executed in a secure sandbox", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table28 = new TechTalk.SpecFlow.Table(new string[] {
                            "Behavior",
                            "Monitoring"});
                table28.AddRow(new string[] {
                            "Network Activity",
                            "Outbound connections"});
                table28.AddRow(new string[] {
                            "File System",
                            "File read/write access"});
                table28.AddRow(new string[] {
                            "System Calls",
                            "OS-level interactions"});
                table28.AddRow(new string[] {
                            "Memory Usage",
                            "Resource consumption"});
#line 58
    testRunner.And("the scan should monitor runtime behavior including:", ((string)(null)), table28, "And ");
#line hidden
#line 64
    testRunner.And("suspicious behavior should be flagged", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 65
    testRunner.And("the execution should be terminated if malicious activity detected", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Dependency vulnerability scanning")]
        [Xunit.TraitAttribute("FeatureTitle", "Security Scanning and Trust Tier Management")]
        [Xunit.TraitAttribute("Description", "Dependency vulnerability scanning")]
        [Xunit.TraitAttribute("Category", "api")]
        [Xunit.TraitAttribute("Category", "security")]
        [Xunit.TraitAttribute("Category", "scanning")]
        [Xunit.TraitAttribute("Category", "dependencies")]
        public void DependencyVulnerabilityScanning()
        {
            string[] tagsOfScenario = new string[] {
                    "api",
                    "security",
                    "scanning",
                    "dependencies"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Dependency vulnerability scanning", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 68
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
  this.FeatureBackground();
#line hidden
#line 69
    testRunner.Given("I have a package with external dependencies", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 70
    testRunner.When("the dependency scan runs", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 71
    testRunner.Then("it should check all dependencies against vulnerability databases", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 72
    testRunner.And("it should identify packages with known CVEs", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 73
    testRunner.And("it should calculate transitive dependency risks", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 74
    testRunner.And("it should recommend dependency updates where available", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 75
    testRunner.And("the overall security score should factor in dependency risks", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Trust tier progression based on scan results")]
        [Xunit.TraitAttribute("FeatureTitle", "Security Scanning and Trust Tier Management")]
        [Xunit.TraitAttribute("Description", "Trust tier progression based on scan results")]
        [Xunit.TraitAttribute("Category", "api")]
        [Xunit.TraitAttribute("Category", "security")]
        [Xunit.TraitAttribute("Category", "trusttier")]
        [Xunit.TraitAttribute("Category", "progression")]
        public void TrustTierProgressionBasedOnScanResults()
        {
            string[] tagsOfScenario = new string[] {
                    "api",
                    "security",
                    "trusttier",
                    "progression"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Trust tier progression based on scan results", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 78
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
  this.FeatureBackground();
#line hidden
#line 79
    testRunner.Given("I have packages with different security scan results", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table29 = new TechTalk.SpecFlow.Table(new string[] {
                            "Security Score",
                            "Vulnerabilities",
                            "Trust Tier"});
                table29.AddRow(new string[] {
                            "9.0-10.0",
                            "None Critical",
                            "Security Audited"});
                table29.AddRow(new string[] {
                            "7.0-8.9",
                            "None High",
                            "Community Trusted"});
                table29.AddRow(new string[] {
                            "5.0-6.9",
                            "Some Medium",
                            "Community Trusted"});
                table29.AddRow(new string[] {
                            "0.0-4.9",
                            "Critical/High",
                            "Unverified"});
#line 80
    testRunner.Then("packages should be assigned trust tiers as follows:", ((string)(null)), table29, "Then ");
#line hidden
#line 86
    testRunner.And("trust tier changes should be logged in audit trail", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 87
    testRunner.And("package consumers should be notified of tier changes", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Manual trust tier promotion")]
        [Xunit.TraitAttribute("FeatureTitle", "Security Scanning and Trust Tier Management")]
        [Xunit.TraitAttribute("Description", "Manual trust tier promotion")]
        [Xunit.TraitAttribute("Category", "api")]
        [Xunit.TraitAttribute("Category", "security")]
        [Xunit.TraitAttribute("Category", "trusttier")]
        [Xunit.TraitAttribute("Category", "manual")]
        public void ManualTrustTierPromotion()
        {
            string[] tagsOfScenario = new string[] {
                    "api",
                    "security",
                    "trusttier",
                    "manual"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Manual trust tier promotion", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 90
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
  this.FeatureBackground();
#line hidden
#line 91
    testRunner.Given("I am authenticated as a security administrator", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 92
    testRunner.And("there is a package with \"Community Trusted\" tier", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 93
    testRunner.When("I manually promote the package to \"Certified\" tier", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 94
    testRunner.Then("the package trust tier should be updated", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 95
    testRunner.And("a manual review audit entry should be created", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 96
    testRunner.And("the promotion should include reviewer notes and timestamp", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 97
    testRunner.And("package users should be notified of the tier upgrade", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Trust tier demotion due to new vulnerabilities")]
        [Xunit.TraitAttribute("FeatureTitle", "Security Scanning and Trust Tier Management")]
        [Xunit.TraitAttribute("Description", "Trust tier demotion due to new vulnerabilities")]
        [Xunit.TraitAttribute("Category", "api")]
        [Xunit.TraitAttribute("Category", "security")]
        [Xunit.TraitAttribute("Category", "trusttier")]
        [Xunit.TraitAttribute("Category", "demotion")]
        public void TrustTierDemotionDueToNewVulnerabilities()
        {
            string[] tagsOfScenario = new string[] {
                    "api",
                    "security",
                    "trusttier",
                    "demotion"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Trust tier demotion due to new vulnerabilities", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 100
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
  this.FeatureBackground();
#line hidden
#line 101
    testRunner.Given("there is a \"Security Audited\" package", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 102
    testRunner.When("new vulnerabilities are discovered in the package", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 103
    testRunner.And("a rescan reveals critical security issues", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 104
    testRunner.Then("the package should be automatically demoted to appropriate tier", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 105
    testRunner.And("all users of the package should be notified", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 106
    testRunner.And("the package should be flagged for immediate attention", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 107
    testRunner.And("remediation guidance should be provided to the publisher", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Manual package rescan request")]
        [Xunit.TraitAttribute("FeatureTitle", "Security Scanning and Trust Tier Management")]
        [Xunit.TraitAttribute("Description", "Manual package rescan request")]
        [Xunit.TraitAttribute("Category", "api")]
        [Xunit.TraitAttribute("Category", "security")]
        [Xunit.TraitAttribute("Category", "scanning")]
        [Xunit.TraitAttribute("Category", "rescan")]
        public void ManualPackageRescanRequest()
        {
            string[] tagsOfScenario = new string[] {
                    "api",
                    "security",
                    "scanning",
                    "rescan"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Manual package rescan request", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 110
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
  this.FeatureBackground();
#line hidden
#line 111
    testRunner.Given("I am the publisher of a package", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 112
    testRunner.And("my package has been updated to fix security issues", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 113
    testRunner.When("I request a manual rescan of my package", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 114
    testRunner.Then("a new security scan should be initiated", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 115
    testRunner.And("the previous scan results should be archived", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 116
    testRunner.And("I should receive notification when the rescan completes", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 117
    testRunner.And("the trust tier should be re-evaluated based on new results", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Scheduled security rescans")]
        [Xunit.TraitAttribute("FeatureTitle", "Security Scanning and Trust Tier Management")]
        [Xunit.TraitAttribute("Description", "Scheduled security rescans")]
        [Xunit.TraitAttribute("Category", "api")]
        [Xunit.TraitAttribute("Category", "security")]
        [Xunit.TraitAttribute("Category", "scanning")]
        [Xunit.TraitAttribute("Category", "scheduled")]
        public void ScheduledSecurityRescans()
        {
            string[] tagsOfScenario = new string[] {
                    "api",
                    "security",
                    "scanning",
                    "scheduled"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Scheduled security rescans", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 120
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
  this.FeatureBackground();
#line hidden
#line 121
    testRunner.Given("there are packages in the registry older than 30 days", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 122
    testRunner.When("the scheduled security scan job runs", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table30 = new TechTalk.SpecFlow.Table(new string[] {
                            "Criteria",
                            "Priority"});
                table30.AddRow(new string[] {
                            "High download count",
                            "High"});
                table30.AddRow(new string[] {
                            "Recent vulnerability",
                            "High"});
                table30.AddRow(new string[] {
                            "Age since last scan",
                            "Medium"});
                table30.AddRow(new string[] {
                            "Trust tier level",
                            "Medium"});
#line 123
    testRunner.Then("packages should be selected for rescanning based on:", ((string)(null)), table30, "Then ");
#line hidden
#line 129
    testRunner.And("rescans should be distributed over time to manage load", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 130
    testRunner.And("scan results should be compared with previous scans", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Security policy enforcement")]
        [Xunit.TraitAttribute("FeatureTitle", "Security Scanning and Trust Tier Management")]
        [Xunit.TraitAttribute("Description", "Security policy enforcement")]
        [Xunit.TraitAttribute("Category", "api")]
        [Xunit.TraitAttribute("Category", "security")]
        [Xunit.TraitAttribute("Category", "policy")]
        [Xunit.TraitAttribute("Category", "enforcement")]
        public void SecurityPolicyEnforcement()
        {
            string[] tagsOfScenario = new string[] {
                    "api",
                    "security",
                    "policy",
                    "enforcement"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Security policy enforcement", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 133
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
  this.FeatureBackground();
#line hidden
#line 134
    testRunner.Given("there are security policies defined for different trust tiers", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 135
    testRunner.When("a package scan completes", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 136
    testRunner.Then("the package should be evaluated against relevant policies", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table31 = new TechTalk.SpecFlow.Table(new string[] {
                            "Policy Violation",
                            "Action"});
                table31.AddRow(new string[] {
                            "Critical vulnerability",
                            "Immediate suspension"});
                table31.AddRow(new string[] {
                            "High vulnerability",
                            "Warning and review flag"});
                table31.AddRow(new string[] {
                            "Policy non-compliance",
                            "Trust tier restriction"});
                table31.AddRow(new string[] {
                            "License incompatibility",
                            "Publisher notification"});
#line 137
    testRunner.And("packages violating policies should be:", ((string)(null)), table31, "And ");
#line hidden
#line 143
    testRunner.And("policy violations should be logged and tracked", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Security scan metadata and reporting")]
        [Xunit.TraitAttribute("FeatureTitle", "Security Scanning and Trust Tier Management")]
        [Xunit.TraitAttribute("Description", "Security scan metadata and reporting")]
        [Xunit.TraitAttribute("Category", "api")]
        [Xunit.TraitAttribute("Category", "security")]
        [Xunit.TraitAttribute("Category", "scanning")]
        [Xunit.TraitAttribute("Category", "metadata")]
        public void SecurityScanMetadataAndReporting()
        {
            string[] tagsOfScenario = new string[] {
                    "api",
                    "security",
                    "scanning",
                    "metadata"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Security scan metadata and reporting", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 146
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
  this.FeatureBackground();
#line hidden
#line 147
    testRunner.Given("I have packages with completed security scans", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 148
    testRunner.When("I request security scan details", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table32 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Description"});
                table32.AddRow(new string[] {
                            "scan_id",
                            "Unique scan identifier"});
                table32.AddRow(new string[] {
                            "scan_type",
                            "Static, dynamic, dependency"});
                table32.AddRow(new string[] {
                            "scan_timestamp",
                            "When scan was performed"});
                table32.AddRow(new string[] {
                            "scan_duration",
                            "Time taken for scan"});
                table32.AddRow(new string[] {
                            "scanner_version",
                            "Version of scanning tools"});
                table32.AddRow(new string[] {
                            "findings_count",
                            "Number of issues found"});
                table32.AddRow(new string[] {
                            "false_positive_count",
                            "Issues marked as FP"});
#line 149
    testRunner.Then("the response should include comprehensive metadata:", ((string)(null)), table32, "Then ");
#line hidden
#line 158
    testRunner.And("historical scan data should be available for comparison", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Security scan performance optimization")]
        [Xunit.TraitAttribute("FeatureTitle", "Security Scanning and Trust Tier Management")]
        [Xunit.TraitAttribute("Description", "Security scan performance optimization")]
        [Xunit.TraitAttribute("Category", "api")]
        [Xunit.TraitAttribute("Category", "security")]
        [Xunit.TraitAttribute("Category", "scanning")]
        [Xunit.TraitAttribute("Category", "performance")]
        public void SecurityScanPerformanceOptimization()
        {
            string[] tagsOfScenario = new string[] {
                    "api",
                    "security",
                    "scanning",
                    "performance"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Security scan performance optimization", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 161
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
  this.FeatureBackground();
#line hidden
#line 162
    testRunner.Given("there are multiple packages queued for scanning", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 163
    testRunner.When("the security scanning system processes the queue", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table33 = new TechTalk.SpecFlow.Table(new string[] {
                            "Priority Factor",
                            "Weight"});
                table33.AddRow(new string[] {
                            "Package popularity",
                            "High"});
                table33.AddRow(new string[] {
                            "Publisher reputation",
                            "High"});
                table33.AddRow(new string[] {
                            "Package complexity",
                            "Medium"});
                table33.AddRow(new string[] {
                            "Previous scan results",
                            "Medium"});
#line 164
    testRunner.Then("scans should be prioritized by:", ((string)(null)), table33, "Then ");
#line hidden
#line 170
    testRunner.And("parallel scanning should be used to optimize throughput", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 171
    testRunner.And("scan results should be cached to avoid redundant scans", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="False positive management")]
        [Xunit.TraitAttribute("FeatureTitle", "Security Scanning and Trust Tier Management")]
        [Xunit.TraitAttribute("Description", "False positive management")]
        [Xunit.TraitAttribute("Category", "api")]
        [Xunit.TraitAttribute("Category", "security")]
        [Xunit.TraitAttribute("Category", "scanning")]
        [Xunit.TraitAttribute("Category", "falsepositives")]
        public void FalsePositiveManagement()
        {
            string[] tagsOfScenario = new string[] {
                    "api",
                    "security",
                    "scanning",
                    "falsepositives"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("False positive management", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 174
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
  this.FeatureBackground();
#line hidden
#line 175
    testRunner.Given("I am a package publisher with scan results containing false positives", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 176
    testRunner.When("I mark specific findings as false positives", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 177
    testRunner.Then("the findings should be marked as dismissed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 178
    testRunner.And("the security score should be recalculated", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 179
    testRunner.And("the false positive markers should be preserved across rescans", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 180
    testRunner.And("security administrators should be able to review FP claims", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Integration with external security databases")]
        [Xunit.TraitAttribute("FeatureTitle", "Security Scanning and Trust Tier Management")]
        [Xunit.TraitAttribute("Description", "Integration with external security databases")]
        [Xunit.TraitAttribute("Category", "api")]
        [Xunit.TraitAttribute("Category", "security")]
        [Xunit.TraitAttribute("Category", "scanning")]
        [Xunit.TraitAttribute("Category", "integration")]
        public void IntegrationWithExternalSecurityDatabases()
        {
            string[] tagsOfScenario = new string[] {
                    "api",
                    "security",
                    "scanning",
                    "integration"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Integration with external security databases", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 183
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
  this.FeatureBackground();
#line hidden
#line 184
    testRunner.When("the security scanning runs", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table34 = new TechTalk.SpecFlow.Table(new string[] {
                            "Database",
                            "Purpose"});
                table34.AddRow(new string[] {
                            "CVE",
                            "Common vulnerabilities"});
                table34.AddRow(new string[] {
                            "NVD",
                            "National vulnerability DB"});
                table34.AddRow(new string[] {
                            "OSV",
                            "Open source vulnerabilities"});
                table34.AddRow(new string[] {
                            "GHSA",
                            "GitHub security advisories"});
#line 185
    testRunner.Then("it should integrate with external vulnerability databases:", ((string)(null)), table34, "Then ");
#line hidden
#line 191
    testRunner.And("database updates should trigger rescans of affected packages", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 192
    testRunner.And("new vulnerability data should be continuously synchronized", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Trust tier filtering for package consumers")]
        [Xunit.TraitAttribute("FeatureTitle", "Security Scanning and Trust Tier Management")]
        [Xunit.TraitAttribute("Description", "Trust tier filtering for package consumers")]
        [Xunit.TraitAttribute("Category", "api")]
        [Xunit.TraitAttribute("Category", "security")]
        [Xunit.TraitAttribute("Category", "trusttier")]
        [Xunit.TraitAttribute("Category", "consumer")]
        public void TrustTierFilteringForPackageConsumers()
        {
            string[] tagsOfScenario = new string[] {
                    "api",
                    "security",
                    "trusttier",
                    "consumer"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Trust tier filtering for package consumers", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 195
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
  this.FeatureBackground();
#line hidden
#line 196
    testRunner.Given("there are packages with various trust tiers", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 197
    testRunner.When("I search for packages with minimum trust tier \"Community Trusted\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 198
    testRunner.Then("only packages meeting the trust tier requirement should be returned", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 199
    testRunner.And("the search results should clearly display trust tier information", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 200
    testRunner.And("packages below the threshold should be excluded from results", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 201
    testRunner.And("clear explanations should be provided for trust tier meanings", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Security scan notifications")]
        [Xunit.TraitAttribute("FeatureTitle", "Security Scanning and Trust Tier Management")]
        [Xunit.TraitAttribute("Description", "Security scan notifications")]
        [Xunit.TraitAttribute("Category", "api")]
        [Xunit.TraitAttribute("Category", "security")]
        [Xunit.TraitAttribute("Category", "scanning")]
        [Xunit.TraitAttribute("Category", "notification")]
        public void SecurityScanNotifications()
        {
            string[] tagsOfScenario = new string[] {
                    "api",
                    "security",
                    "scanning",
                    "notification"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Security scan notifications", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 204
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
  this.FeatureBackground();
#line hidden
#line 205
    testRunner.Given("I am a publisher with packages in the registry", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 206
    testRunner.When("security scans complete for my packages", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table35 = new TechTalk.SpecFlow.Table(new string[] {
                            "Event Type",
                            "Notification Method"});
                table35.AddRow(new string[] {
                            "Scan completion",
                            "Email, API webhook"});
                table35.AddRow(new string[] {
                            "New vulnerabilities",
                            "Email, dashboard"});
                table35.AddRow(new string[] {
                            "Trust tier changes",
                            "Email, API webhook"});
                table35.AddRow(new string[] {
                            "Policy violations",
                            "Email, urgent flag"});
#line 207
    testRunner.Then("I should receive notifications for:", ((string)(null)), table35, "Then ");
#line hidden
#line 213
    testRunner.And("notifications should include actionable information", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 214
    testRunner.And("I should be able to configure notification preferences", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Security compliance reporting")]
        [Xunit.TraitAttribute("FeatureTitle", "Security Scanning and Trust Tier Management")]
        [Xunit.TraitAttribute("Description", "Security compliance reporting")]
        [Xunit.TraitAttribute("Category", "api")]
        [Xunit.TraitAttribute("Category", "security")]
        [Xunit.TraitAttribute("Category", "compliance")]
        [Xunit.TraitAttribute("Category", "reporting")]
        public void SecurityComplianceReporting()
        {
            string[] tagsOfScenario = new string[] {
                    "api",
                    "security",
                    "compliance",
                    "reporting"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Security compliance reporting", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 217
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
  this.FeatureBackground();
#line hidden
#line 218
    testRunner.Given("I am a security administrator", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 219
    testRunner.When("I request security compliance reports", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table36 = new TechTalk.SpecFlow.Table(new string[] {
                            "Report Section",
                            "Information"});
                table36.AddRow(new string[] {
                            "Scan Coverage",
                            "% of packages scanned"});
                table36.AddRow(new string[] {
                            "Vulnerability Trends",
                            "New vs resolved issues"});
                table36.AddRow(new string[] {
                            "Trust Tier Distribution",
                            "Breakdown by tier"});
                table36.AddRow(new string[] {
                            "Policy Compliance",
                            "Violations by policy"});
                table36.AddRow(new string[] {
                            "Response Times",
                            "Time to address issues"});
#line 220
    testRunner.Then("the reports should include:", ((string)(null)), table36, "Then ");
#line hidden
#line 227
    testRunner.And("reports should be available in multiple formats", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 228
    testRunner.And("historical data should be included for trend analysis", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                SecurityScanningAndTrustTierManagementFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                SecurityScanningAndTrustTierManagementFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
